version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src # Mount the source code directory to enable live reload
    env_file:
      - .env # Point to your .env file
    environment:
      - FLASK_ENV=development # Ensure Flask is running in development mode
    command: gunicorn --reload -w 4 -b 0.0.0.0:8080 src.server:app
